namespace OutpatientFeeInterfaceInstance.IInvoicePrint
{
    partial class ucInvoicePrintFP
    {
        /// <summary> 
        /// 必需的设计器变量。
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// 清理所有正在使用的资源。
        /// </summary>
        /// <param name="disposing">如果应释放托管资源，为 true；否则为 false。</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region 组件设计器生成的代码

        /// <summary> 
        /// 设计器支持所需的方法 - 不要
        /// 使用代码编辑器修改此方法的内容。
        /// </summary>
        private void InitializeComponent()
        {
            FarPoint.Win.Spread.TipAppearance tipAppearance1 = new FarPoint.Win.Spread.TipAppearance();
            System.Globalization.CultureInfo cultureInfo = new System.Globalization.CultureInfo("zh-CN", false);
            FarPoint.Win.Spread.CellType.RichTextCellType richTextCellType1 = new FarPoint.Win.Spread.CellType.RichTextCellType();
            FarPoint.Win.Spread.CellType.RichTextCellType richTextCellType2 = new FarPoint.Win.Spread.CellType.RichTextCellType();
            FarPoint.Win.Spread.CellType.RichTextCellType richTextCellType3 = new FarPoint.Win.Spread.CellType.RichTextCellType();
            this.neuSpread1 = new Neusoft.FrameWork.WinForms.Controls.NeuSpread();
            this.neuSpread1_Sheet1 = new FarPoint.Win.Spread.SheetView();
            ((System.ComponentModel.ISupportInitialize)(this.neuSpread1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.neuSpread1_Sheet1)).BeginInit();
            this.SuspendLayout();
            // 
            // neuSpread1
            // 
            this.neuSpread1.About = "3.0.2004.2005";
            this.neuSpread1.AccessibleDescription = "neuSpread1, Sheet1, Row 0, Column 0, ";
            this.neuSpread1.BackColor = System.Drawing.Color.White;
            this.neuSpread1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.neuSpread1.FileName = "";
            this.neuSpread1.HorizontalScrollBarPolicy = FarPoint.Win.Spread.ScrollBarPolicy.AsNeeded;
            this.neuSpread1.IsAutoSaveGridStatus = false;
            this.neuSpread1.IsCanCustomConfigColumn = false;
            this.neuSpread1.Location = new System.Drawing.Point(0, 0);
            this.neuSpread1.Name = "neuSpread1";
            this.neuSpread1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.neuSpread1.Sheets.AddRange(new FarPoint.Win.Spread.SheetView[] {
            this.neuSpread1_Sheet1});
            this.neuSpread1.Size = new System.Drawing.Size(1048, 470);
            this.neuSpread1.Style = Neusoft.FrameWork.WinForms.Controls.StyleType.Fixed3D;
            this.neuSpread1.TabIndex = 0;
            tipAppearance1.BackColor = System.Drawing.SystemColors.Info;
            tipAppearance1.Font = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            tipAppearance1.ForeColor = System.Drawing.SystemColors.InfoText;
            this.neuSpread1.TextTipAppearance = tipAppearance1;
            this.neuSpread1.VerticalScrollBarPolicy = FarPoint.Win.Spread.ScrollBarPolicy.AsNeeded;
            // 
            // neuSpread1_Sheet1
            // 
            this.neuSpread1_Sheet1.Reset();
            this.neuSpread1_Sheet1.SheetName = "Sheet1";
            // Formulas and custom names must be loaded with R1C1 reference style
            this.neuSpread1_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.R1C1;
            this.neuSpread1_Sheet1.ColumnCount = 22;
            this.neuSpread1_Sheet1.RowCount = 28;
            this.neuSpread1_Sheet1.Cells.Get(0, 2).Value = "调位置行";
            richTextCellType1.Multiline = true;
            richTextCellType1.WordWrap = true;
            this.neuSpread1_Sheet1.Cells.Get(1, 1).CellType = richTextCellType1;
            this.neuSpread1_Sheet1.Cells.Get(1, 1).ColumnSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(1, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.neuSpread1_Sheet1.Cells.Get(1, 1).Value = "{\\rtf1\\ansi\\ansicpg936\\deff0{\\fonttbl{\\f0\\fswiss\\fcharset0 Arial;}{\\f1\\fnil\\fchar" +
                "set134 \\\'cb\\\'ce\\\'cc\\\'e5;}}\r\n\\viewkind4\\uc1\\pard\\qc\\lang2052\\f0\\fs18 -a-\\par\r\n-b-" +
                "\\f1\\par\r\n}\r\n";
            this.neuSpread1_Sheet1.Cells.Get(1, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.neuSpread1_Sheet1.Cells.Get(1, 2).ParseFormatInfo = ((System.Globalization.NumberFormatInfo)(cultureInfo.NumberFormat.Clone()));
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(1, 2).ParseFormatInfo)).NumberDecimalDigits = 0;
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(1, 2).ParseFormatInfo)).NumberGroupSizes = new int[] {
        0};
            this.neuSpread1_Sheet1.Cells.Get(1, 2).ParseFormatString = "n";
            this.neuSpread1_Sheet1.Cells.Get(1, 2).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(1, 2).Value = ((long)(9000059207));
            this.neuSpread1_Sheet1.Cells.Get(1, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.neuSpread1_Sheet1.Cells.Get(1, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            richTextCellType2.Multiline = true;
            richTextCellType2.WordWrap = true;
            this.neuSpread1_Sheet1.Cells.Get(1, 4).CellType = richTextCellType2;
            this.neuSpread1_Sheet1.Cells.Get(1, 4).ColumnSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(1, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.neuSpread1_Sheet1.Cells.Get(1, 4).Value = "{\\rtf1\\ansi\\ansicpg1252\\deff0{\\fonttbl{\\f0\\fswiss\\fcharset0 Arial;}{\\f1\\fnil\\fcha" +
                "rset134 \\\'cb\\\'ce\\\'cc\\\'e5;}}\r\n\\viewkind4\\uc1\\pard\\qc\\lang2052\\f0\\fs18 fdsa\\par\r\nf" +
                "dsae\\f1\\par\r\n}\r\n";
            this.neuSpread1_Sheet1.Cells.Get(1, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.neuSpread1_Sheet1.Cells.Get(1, 5).ParseFormatInfo = ((System.Globalization.NumberFormatInfo)(cultureInfo.NumberFormat.Clone()));
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(1, 5).ParseFormatInfo)).NumberDecimalDigits = 0;
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(1, 5).ParseFormatInfo)).NumberGroupSizes = new int[] {
        0};
            this.neuSpread1_Sheet1.Cells.Get(1, 5).ParseFormatString = "n";
            this.neuSpread1_Sheet1.Cells.Get(1, 5).Tag = "value2";
            this.neuSpread1_Sheet1.Cells.Get(1, 5).Value = ((long)(9000059207));
            this.neuSpread1_Sheet1.Cells.Get(1, 5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.neuSpread1_Sheet1.Cells.Get(1, 6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            richTextCellType3.Multiline = true;
            richTextCellType3.WordWrap = true;
            this.neuSpread1_Sheet1.Cells.Get(1, 7).CellType = richTextCellType3;
            this.neuSpread1_Sheet1.Cells.Get(1, 7).ColumnSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(1, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.neuSpread1_Sheet1.Cells.Get(1, 7).Value = "{\\rtf1\\ansi\\ansicpg1252\\deff0{\\fonttbl{\\f0\\fswiss\\fcharset0 Arial;}{\\f1\\fnil\\fcha" +
                "rset134 \\\'cb\\\'ce\\\'cc\\\'e5;}}\r\n\\viewkind4\\uc1\\pard\\qc\\lang2052\\f0\\fs18 fdsa\\par\r\nf" +
                "dsae\\f1\\par\r\n}\r\n";
            this.neuSpread1_Sheet1.Cells.Get(1, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.neuSpread1_Sheet1.Cells.Get(1, 8).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(1, 8).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Bottom;
            this.neuSpread1_Sheet1.Cells.Get(1, 9).ColumnSpan = 4;
            this.neuSpread1_Sheet1.Cells.Get(1, 9).Font = new System.Drawing.Font("宋体", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.neuSpread1_Sheet1.Cells.Get(1, 9).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.neuSpread1_Sheet1.Cells.Get(1, 9).Tag = "value2";
            this.neuSpread1_Sheet1.Cells.Get(1, 9).Value = "郑州大学第一附属医院";
            this.neuSpread1_Sheet1.Cells.Get(1, 9).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.neuSpread1_Sheet1.Cells.Get(1, 13).ParseFormatInfo = ((System.Globalization.NumberFormatInfo)(cultureInfo.NumberFormat.Clone()));
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(1, 13).ParseFormatInfo)).NumberDecimalDigits = 0;
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(1, 13).ParseFormatInfo)).NumberGroupSizes = new int[] {
        0};
            this.neuSpread1_Sheet1.Cells.Get(1, 13).ParseFormatString = "n";
            this.neuSpread1_Sheet1.Cells.Get(1, 13).Value = 1;
            this.neuSpread1_Sheet1.Cells.Get(1, 16).ParseFormatInfo = ((System.Globalization.NumberFormatInfo)(cultureInfo.NumberFormat.Clone()));
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(1, 16).ParseFormatInfo)).NumberDecimalDigits = 0;
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(1, 16).ParseFormatInfo)).NumberGroupSizes = new int[] {
        0};
            this.neuSpread1_Sheet1.Cells.Get(1, 16).ParseFormatString = "n";
            this.neuSpread1_Sheet1.Cells.Get(1, 16).Value = 2;
            this.neuSpread1_Sheet1.Cells.Get(1, 19).ParseFormatInfo = ((System.Globalization.NumberFormatInfo)(cultureInfo.NumberFormat.Clone()));
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(1, 19).ParseFormatInfo)).NumberDecimalDigits = 0;
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(1, 19).ParseFormatInfo)).NumberGroupSizes = new int[] {
        0};
            this.neuSpread1_Sheet1.Cells.Get(1, 19).ParseFormatString = "n";
            this.neuSpread1_Sheet1.Cells.Get(1, 19).Value = 3;
            this.neuSpread1_Sheet1.Cells.Get(2, 4).Tag = "value2";
            this.neuSpread1_Sheet1.Cells.Get(2, 4).Value = "自费";
            this.neuSpread1_Sheet1.Cells.Get(2, 5).Tag = "value2";
            this.neuSpread1_Sheet1.Cells.Get(2, 5).Value = "账户余额";
            this.neuSpread1_Sheet1.Cells.Get(2, 7).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(2, 7).Value = "自费";
            this.neuSpread1_Sheet1.Cells.Get(2, 8).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(2, 8).Value = "账户余额";
            this.neuSpread1_Sheet1.Cells.Get(3, 1).Value = "现金";
            this.neuSpread1_Sheet1.Cells.Get(3, 2).Value = "value1";
            this.neuSpread1_Sheet1.Cells.Get(3, 4).Value = "姓名";
            this.neuSpread1_Sheet1.Cells.Get(3, 5).Tag = "value2";
            this.neuSpread1_Sheet1.Cells.Get(3, 5).Value = "张三";
            this.neuSpread1_Sheet1.Cells.Get(3, 7).Value = "姓名";
            this.neuSpread1_Sheet1.Cells.Get(3, 8).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(3, 8).Value = "张三";
            this.neuSpread1_Sheet1.Cells.Get(4, 1).Value = "日期";
            this.neuSpread1_Sheet1.Cells.Get(4, 2).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(4, 4).Value = "医保号";
            this.neuSpread1_Sheet1.Cells.Get(4, 5).ParseFormatInfo = ((System.Globalization.NumberFormatInfo)(cultureInfo.NumberFormat.Clone()));
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(4, 5).ParseFormatInfo)).NumberDecimalDigits = 0;
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(4, 5).ParseFormatInfo)).NumberGroupSizes = new int[] {
        0};
            this.neuSpread1_Sheet1.Cells.Get(4, 5).ParseFormatString = "n";
            this.neuSpread1_Sheet1.Cells.Get(4, 5).Tag = "value2";
            this.neuSpread1_Sheet1.Cells.Get(4, 5).Value = 123;
            this.neuSpread1_Sheet1.Cells.Get(4, 7).Value = "项目";
            this.neuSpread1_Sheet1.Cells.Get(4, 8).Value = "单位";
            this.neuSpread1_Sheet1.Cells.Get(4, 9).ColumnSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(4, 9).Value = "标准";
            this.neuSpread1_Sheet1.Cells.Get(4, 11).Value = "数量";
            this.neuSpread1_Sheet1.Cells.Get(4, 12).Value = "金额";
            this.neuSpread1_Sheet1.Cells.Get(4, 14).Value = "科室";
            this.neuSpread1_Sheet1.Cells.Get(4, 17).Value = "科室";
            this.neuSpread1_Sheet1.Cells.Get(4, 20).Value = "科室";
            this.neuSpread1_Sheet1.Cells.Get(5, 1).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(5, 1).Value = "项目";
            this.neuSpread1_Sheet1.Cells.Get(5, 2).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(5, 2).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(5, 2).Value = "金额";
            this.neuSpread1_Sheet1.Cells.Get(5, 4).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(5, 4).Value = "项目";
            this.neuSpread1_Sheet1.Cells.Get(5, 5).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(5, 5).Value = "金额";
            this.neuSpread1_Sheet1.Cells.Get(5, 7).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(5, 7).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(5, 7).Value = "西药费1";
            this.neuSpread1_Sheet1.Cells.Get(5, 8).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(5, 8).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(5, 9).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(5, 9).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(5, 10).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(5, 10).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(5, 11).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(5, 11).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(5, 12).ParseFormatInfo = ((System.Globalization.NumberFormatInfo)(cultureInfo.NumberFormat.Clone()));
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(5, 12).ParseFormatInfo)).NumberDecimalDigits = 0;
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(5, 12).ParseFormatInfo)).NumberGroupSizes = new int[] {
        0};
            this.neuSpread1_Sheet1.Cells.Get(5, 12).ParseFormatString = "n";
            this.neuSpread1_Sheet1.Cells.Get(5, 12).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(5, 12).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(5, 12).Value = 2;
            this.neuSpread1_Sheet1.Cells.Get(5, 14).ColumnSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(5, 14).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.neuSpread1_Sheet1.Cells.Get(5, 14).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(5, 14).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(5, 14).Value = "耳鼻喉";
            this.neuSpread1_Sheet1.Cells.Get(5, 15).Value = "耳鼻喉";
            this.neuSpread1_Sheet1.Cells.Get(5, 17).ColumnSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(5, 17).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(5, 17).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(5, 20).ColumnSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(5, 20).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(5, 20).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(6, 4).Value = "项目";
            this.neuSpread1_Sheet1.Cells.Get(6, 5).Value = "金额";
            this.neuSpread1_Sheet1.Cells.Get(6, 7).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(6, 7).Value = "西药费1";
            this.neuSpread1_Sheet1.Cells.Get(6, 8).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(6, 9).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(6, 10).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(6, 11).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(6, 12).ParseFormatInfo = ((System.Globalization.NumberFormatInfo)(cultureInfo.NumberFormat.Clone()));
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(6, 12).ParseFormatInfo)).NumberDecimalDigits = 0;
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(6, 12).ParseFormatInfo)).NumberGroupSizes = new int[] {
        0};
            this.neuSpread1_Sheet1.Cells.Get(6, 12).ParseFormatString = "n";
            this.neuSpread1_Sheet1.Cells.Get(6, 12).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(6, 12).Value = 2;
            this.neuSpread1_Sheet1.Cells.Get(7, 1).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(7, 1).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(7, 1).Value = "西药费1";
            this.neuSpread1_Sheet1.Cells.Get(7, 2).ParseFormatInfo = ((System.Globalization.NumberFormatInfo)(cultureInfo.NumberFormat.Clone()));
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(7, 2).ParseFormatInfo)).NumberDecimalDigits = 0;
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(7, 2).ParseFormatInfo)).NumberGroupSizes = new int[] {
        0};
            this.neuSpread1_Sheet1.Cells.Get(7, 2).ParseFormatString = "n";
            this.neuSpread1_Sheet1.Cells.Get(7, 2).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(7, 2).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(7, 2).Value = 2;
            this.neuSpread1_Sheet1.Cells.Get(7, 4).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(7, 4).Value = "自费费用";
            this.neuSpread1_Sheet1.Cells.Get(7, 5).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(7, 5).Tag = "value2";
            this.neuSpread1_Sheet1.Cells.Get(7, 7).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(7, 7).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(7, 8).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(7, 8).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(7, 9).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(7, 9).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(7, 10).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(7, 10).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(7, 11).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(7, 11).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(7, 12).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(7, 12).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(8, 4).Value = "个人自付：";
            this.neuSpread1_Sheet1.Cells.Get(8, 5).Tag = "value2";
            this.neuSpread1_Sheet1.Cells.Get(8, 7).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(8, 8).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(8, 9).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(8, 10).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(8, 11).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(8, 12).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(9, 1).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(9, 1).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(9, 2).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(9, 2).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(9, 4).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(9, 4).Value = "个人自付";
            this.neuSpread1_Sheet1.Cells.Get(9, 5).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(9, 5).Tag = "value2";
            this.neuSpread1_Sheet1.Cells.Get(9, 7).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(9, 7).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(9, 8).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(9, 8).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(9, 9).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(9, 9).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(9, 10).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(9, 10).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(9, 11).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(9, 11).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(9, 12).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(9, 12).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(9, 14).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(9, 14).Value = "姓名";
            this.neuSpread1_Sheet1.Cells.Get(9, 17).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(9, 17).Value = "姓名";
            this.neuSpread1_Sheet1.Cells.Get(9, 20).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(9, 20).Value = "姓名";
            this.neuSpread1_Sheet1.Cells.Get(10, 4).Value = "按比例自付";
            this.neuSpread1_Sheet1.Cells.Get(10, 5).Tag = "value2";
            this.neuSpread1_Sheet1.Cells.Get(10, 7).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(10, 8).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(10, 9).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(10, 10).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(10, 11).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(10, 12).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(11, 1).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(11, 1).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(11, 2).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(11, 2).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(11, 4).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(11, 4).Value = "起付标准";
            this.neuSpread1_Sheet1.Cells.Get(11, 5).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(11, 5).Tag = "value2";
            this.neuSpread1_Sheet1.Cells.Get(11, 7).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(11, 7).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(11, 8).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(11, 8).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(11, 9).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(11, 9).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(11, 10).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(11, 10).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(11, 11).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(11, 11).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(11, 12).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(11, 12).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(11, 14).ColumnSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(11, 14).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.neuSpread1_Sheet1.Cells.Get(11, 14).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(11, 14).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(11, 14).Value = "张三";
            this.neuSpread1_Sheet1.Cells.Get(11, 17).ColumnSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(11, 17).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(11, 17).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(11, 20).ColumnSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(11, 20).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(11, 20).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(12, 4).Value = "大额记账";
            this.neuSpread1_Sheet1.Cells.Get(12, 5).Tag = "value2";
            this.neuSpread1_Sheet1.Cells.Get(12, 7).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(12, 8).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(12, 9).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(12, 10).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(12, 11).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(12, 12).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(13, 1).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(13, 1).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(13, 2).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(13, 2).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(13, 4).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(13, 4).Value = "按比例自负";
            this.neuSpread1_Sheet1.Cells.Get(13, 5).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(13, 5).Tag = "value2";
            this.neuSpread1_Sheet1.Cells.Get(13, 7).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(13, 7).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(13, 8).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(13, 8).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(13, 9).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(13, 9).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(13, 10).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(13, 10).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(13, 11).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(13, 11).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(13, 12).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(13, 12).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(14, 5).Tag = "value2";
            this.neuSpread1_Sheet1.Cells.Get(14, 7).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(14, 7).Value = "自费费用";
            this.neuSpread1_Sheet1.Cells.Get(14, 8).ParseFormatInfo = ((System.Globalization.NumberFormatInfo)(cultureInfo.NumberFormat.Clone()));
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(14, 8).ParseFormatInfo)).NumberDecimalDigits = 0;
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(14, 8).ParseFormatInfo)).NumberGroupSizes = new int[] {
        0};
            this.neuSpread1_Sheet1.Cells.Get(14, 8).ParseFormatString = "n";
            this.neuSpread1_Sheet1.Cells.Get(14, 8).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(14, 8).Value = 10;
            this.neuSpread1_Sheet1.Cells.Get(14, 9).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(14, 9).Value = "个人自付";
            this.neuSpread1_Sheet1.Cells.Get(14, 10).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(14, 11).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(14, 11).Value = "起付标准";
            this.neuSpread1_Sheet1.Cells.Get(14, 12).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(15, 1).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(15, 1).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(15, 2).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(15, 2).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(15, 4).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(15, 4).Value = "统筹记账";
            this.neuSpread1_Sheet1.Cells.Get(15, 5).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(15, 5).Tag = "value2";
            this.neuSpread1_Sheet1.Cells.Get(15, 7).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(15, 7).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(15, 8).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(15, 8).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(15, 9).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(15, 9).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(15, 10).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(15, 10).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(15, 11).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(15, 11).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(15, 12).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(15, 12).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(15, 14).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(15, 14).Value = "项目";
            this.neuSpread1_Sheet1.Cells.Get(15, 15).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(15, 17).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(15, 17).Value = "项目";
            this.neuSpread1_Sheet1.Cells.Get(15, 18).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(15, 20).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(15, 20).Value = "项目";
            this.neuSpread1_Sheet1.Cells.Get(15, 21).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(16, 2).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(16, 5).Tag = "value2";
            this.neuSpread1_Sheet1.Cells.Get(16, 7).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(16, 7).Value = "公务员记账";
            this.neuSpread1_Sheet1.Cells.Get(16, 8).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(16, 9).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(16, 9).Value = "个人账户";
            this.neuSpread1_Sheet1.Cells.Get(16, 10).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(16, 11).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(16, 11).Value = "现金支付";
            this.neuSpread1_Sheet1.Cells.Get(16, 12).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(17, 1).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(17, 1).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(17, 2).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(17, 2).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(17, 4).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(17, 4).Value = "大额记账";
            this.neuSpread1_Sheet1.Cells.Get(17, 5).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(17, 5).Tag = "value2";
            this.neuSpread1_Sheet1.Cells.Get(17, 7).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(17, 7).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(17, 7).Value = "西药费7";
            this.neuSpread1_Sheet1.Cells.Get(17, 8).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(17, 8).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(17, 9).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(17, 9).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(17, 10).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(17, 10).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(17, 11).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(17, 11).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(17, 12).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(17, 12).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(17, 14).ColumnSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(17, 14).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.neuSpread1_Sheet1.Cells.Get(17, 14).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(17, 14).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(17, 14).Value = "2西药费1";
            this.neuSpread1_Sheet1.Cells.Get(17, 17).ColumnSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(17, 17).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(17, 17).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(17, 20).ColumnSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(17, 20).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(17, 20).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(18, 1).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(18, 2).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(18, 5).Tag = "value2";
            this.neuSpread1_Sheet1.Cells.Get(18, 7).Value = "流水号";
            this.neuSpread1_Sheet1.Cells.Get(18, 8).ParseFormatInfo = ((System.Globalization.NumberFormatInfo)(cultureInfo.NumberFormat.Clone()));
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(18, 8).ParseFormatInfo)).NumberDecimalDigits = 0;
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(18, 8).ParseFormatInfo)).NumberGroupSizes = new int[] {
        0};
            this.neuSpread1_Sheet1.Cells.Get(18, 8).ParseFormatString = "n";
            this.neuSpread1_Sheet1.Cells.Get(18, 8).Value = 17;
            this.neuSpread1_Sheet1.Cells.Get(19, 1).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(19, 1).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(19, 2).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(19, 2).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(19, 4).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(19, 4).Value = "公务员记账";
            this.neuSpread1_Sheet1.Cells.Get(19, 5).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(19, 5).Tag = "value2";
            this.neuSpread1_Sheet1.Cells.Get(19, 7).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(19, 7).Value = "自费费用";
            this.neuSpread1_Sheet1.Cells.Get(19, 8).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(19, 8).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(19, 9).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(19, 9).Value = "个人自付";
            this.neuSpread1_Sheet1.Cells.Get(19, 10).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(19, 10).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(19, 11).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(19, 11).Value = "起付标准";
            this.neuSpread1_Sheet1.Cells.Get(19, 12).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(19, 12).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(19, 14).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(19, 14).Value = "金额";
            this.neuSpread1_Sheet1.Cells.Get(19, 17).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(19, 17).Value = "金额";
            this.neuSpread1_Sheet1.Cells.Get(19, 20).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(19, 20).Value = "金额";
            this.neuSpread1_Sheet1.Cells.Get(20, 1).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(20, 2).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(20, 5).Tag = "value2";
            this.neuSpread1_Sheet1.Cells.Get(20, 7).Value = "自费费用";
            this.neuSpread1_Sheet1.Cells.Get(20, 8).ParseFormatInfo = ((System.Globalization.NumberFormatInfo)(cultureInfo.NumberFormat.Clone()));
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(20, 8).ParseFormatInfo)).NumberDecimalDigits = 0;
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(20, 8).ParseFormatInfo)).NumberGroupSizes = new int[] {
        0};
            this.neuSpread1_Sheet1.Cells.Get(20, 8).ParseFormatString = "n";
            this.neuSpread1_Sheet1.Cells.Get(20, 8).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(20, 8).Value = 10;
            this.neuSpread1_Sheet1.Cells.Get(20, 9).Value = "个人自付";
            this.neuSpread1_Sheet1.Cells.Get(20, 10).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(20, 11).Value = "起付标准";
            this.neuSpread1_Sheet1.Cells.Get(20, 12).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(21, 1).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(21, 1).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(21, 2).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(21, 2).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(21, 4).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(21, 4).Value = "个人账户";
            this.neuSpread1_Sheet1.Cells.Get(21, 5).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(21, 5).Tag = "value2";
            this.neuSpread1_Sheet1.Cells.Get(21, 7).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(21, 7).Value = "按比例自付";
            this.neuSpread1_Sheet1.Cells.Get(21, 8).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(21, 8).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(21, 9).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(21, 9).Value = "统筹记账";
            this.neuSpread1_Sheet1.Cells.Get(21, 10).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(21, 10).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(21, 11).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(21, 11).Value = "大额记账";
            this.neuSpread1_Sheet1.Cells.Get(21, 12).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(21, 12).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(21, 14).ColumnSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(21, 14).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.neuSpread1_Sheet1.Cells.Get(21, 14).ParseFormatInfo = ((System.Globalization.NumberFormatInfo)(cultureInfo.NumberFormat.Clone()));
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(21, 14).ParseFormatInfo)).NumberDecimalDigits = 0;
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(21, 14).ParseFormatInfo)).NumberGroupSizes = new int[] {
        0};
            this.neuSpread1_Sheet1.Cells.Get(21, 14).ParseFormatString = "n";
            this.neuSpread1_Sheet1.Cells.Get(21, 14).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(21, 14).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(21, 14).Value = 2;
            this.neuSpread1_Sheet1.Cells.Get(21, 15).ParseFormatInfo = ((System.Globalization.NumberFormatInfo)(cultureInfo.NumberFormat.Clone()));
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(21, 15).ParseFormatInfo)).NumberDecimalDigits = 0;
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(21, 15).ParseFormatInfo)).NumberGroupSizes = new int[] {
        0};
            this.neuSpread1_Sheet1.Cells.Get(21, 15).ParseFormatString = "n";
            this.neuSpread1_Sheet1.Cells.Get(21, 15).Value = 2;
            this.neuSpread1_Sheet1.Cells.Get(21, 17).ColumnSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(21, 17).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.neuSpread1_Sheet1.Cells.Get(21, 17).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(21, 17).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(21, 20).ColumnSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(21, 20).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.neuSpread1_Sheet1.Cells.Get(21, 20).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(21, 20).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(22, 1).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(22, 2).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(22, 5).Tag = "value2";
            this.neuSpread1_Sheet1.Cells.Get(22, 7).Value = "公务员记账";
            this.neuSpread1_Sheet1.Cells.Get(22, 8).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(22, 9).Value = "个人账户";
            this.neuSpread1_Sheet1.Cells.Get(22, 10).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(22, 11).Value = "现金支付";
            this.neuSpread1_Sheet1.Cells.Get(22, 12).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(23, 1).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(23, 1).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(23, 2).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(23, 2).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(23, 4).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(23, 4).Value = "现金支付";
            this.neuSpread1_Sheet1.Cells.Get(23, 5).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(23, 5).Tag = "value2";
            this.neuSpread1_Sheet1.Cells.Get(23, 7).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(23, 7).Value = "公务员记账";
            this.neuSpread1_Sheet1.Cells.Get(23, 8).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(23, 8).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(23, 9).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(23, 9).Value = "个人账户";
            this.neuSpread1_Sheet1.Cells.Get(23, 10).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(23, 10).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(23, 11).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(23, 11).Value = "现金支付";
            this.neuSpread1_Sheet1.Cells.Get(23, 12).ParseFormatInfo = ((System.Globalization.NumberFormatInfo)(cultureInfo.NumberFormat.Clone()));
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(23, 12).ParseFormatInfo)).NumberDecimalDigits = 0;
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(23, 12).ParseFormatInfo)).NumberGroupSizes = new int[] {
        0};
            this.neuSpread1_Sheet1.Cells.Get(23, 12).ParseFormatString = "n";
            this.neuSpread1_Sheet1.Cells.Get(23, 12).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(23, 12).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(23, 12).Value = 2;
            this.neuSpread1_Sheet1.Cells.Get(24, 2).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(25, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.neuSpread1_Sheet1.Cells.Get(25, 1).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(25, 1).Value = "合计";
            this.neuSpread1_Sheet1.Cells.Get(25, 2).ParseFormatInfo = ((System.Globalization.NumberFormatInfo)(cultureInfo.NumberFormat.Clone()));
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(25, 2).ParseFormatInfo)).NumberDecimalDigits = 0;
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(25, 2).ParseFormatInfo)).NumberGroupSizes = new int[] {
        0};
            this.neuSpread1_Sheet1.Cells.Get(25, 2).ParseFormatString = "n";
            this.neuSpread1_Sheet1.Cells.Get(25, 2).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(25, 2).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(25, 2).Value = 2;
            this.neuSpread1_Sheet1.Cells.Get(25, 4).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(25, 4).Value = "合计";
            this.neuSpread1_Sheet1.Cells.Get(25, 5).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(25, 5).Tag = "value2";
            this.neuSpread1_Sheet1.Cells.Get(25, 7).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(25, 7).Value = "合计";
            this.neuSpread1_Sheet1.Cells.Get(25, 8).ColumnSpan = 4;
            this.neuSpread1_Sheet1.Cells.Get(25, 8).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.neuSpread1_Sheet1.Cells.Get(25, 8).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(25, 8).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(25, 8).Value = "贰元";
            this.neuSpread1_Sheet1.Cells.Get(25, 9).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(25, 10).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(25, 11).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(25, 12).ParseFormatInfo = ((System.Globalization.NumberFormatInfo)(cultureInfo.NumberFormat.Clone()));
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(25, 12).ParseFormatInfo)).NumberDecimalDigits = 0;
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(25, 12).ParseFormatInfo)).NumberGroupSizes = new int[] {
        0};
            this.neuSpread1_Sheet1.Cells.Get(25, 12).ParseFormatString = "n";
            this.neuSpread1_Sheet1.Cells.Get(25, 12).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(25, 12).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(25, 12).Value = 2;
            this.neuSpread1_Sheet1.Cells.Get(25, 14).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(25, 14).Value = "日期";
            this.neuSpread1_Sheet1.Cells.Get(25, 15).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(25, 15).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(25, 17).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(25, 17).Value = "日期";
            this.neuSpread1_Sheet1.Cells.Get(25, 18).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(25, 18).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(25, 20).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(25, 20).Value = "日期";
            this.neuSpread1_Sheet1.Cells.Get(25, 21).RowSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(25, 21).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(26, 2).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(26, 5).Tag = "value2";
            this.neuSpread1_Sheet1.Cells.Get(27, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.neuSpread1_Sheet1.Cells.Get(27, 1).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(27, 1).Value = "流水号";
            this.neuSpread1_Sheet1.Cells.Get(27, 2).ColumnSpan = 2;
            this.neuSpread1_Sheet1.Cells.Get(27, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.neuSpread1_Sheet1.Cells.Get(27, 2).Tag = "value1";
            this.neuSpread1_Sheet1.Cells.Get(27, 2).Value = "制单";
            this.neuSpread1_Sheet1.Cells.Get(27, 4).Value = "流水号";
            this.neuSpread1_Sheet1.Cells.Get(27, 5).Tag = "value2";
            this.neuSpread1_Sheet1.Cells.Get(27, 7).Value = "流水号";
            this.neuSpread1_Sheet1.Cells.Get(27, 8).ParseFormatInfo = ((System.Globalization.NumberFormatInfo)(cultureInfo.NumberFormat.Clone()));
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(27, 8).ParseFormatInfo)).NumberDecimalDigits = 0;
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(27, 8).ParseFormatInfo)).NumberGroupSizes = new int[] {
        0};
            this.neuSpread1_Sheet1.Cells.Get(27, 8).ParseFormatString = "n";
            this.neuSpread1_Sheet1.Cells.Get(27, 8).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(27, 8).Value = 17;
            this.neuSpread1_Sheet1.Cells.Get(27, 9).Value = "制单";
            this.neuSpread1_Sheet1.Cells.Get(27, 10).ParseFormatInfo = ((System.Globalization.NumberFormatInfo)(cultureInfo.NumberFormat.Clone()));
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(27, 10).ParseFormatInfo)).NumberDecimalDigits = 0;
            ((System.Globalization.NumberFormatInfo)(this.neuSpread1_Sheet1.Cells.Get(27, 10).ParseFormatInfo)).NumberGroupSizes = new int[] {
        0};
            this.neuSpread1_Sheet1.Cells.Get(27, 10).ParseFormatString = "n";
            this.neuSpread1_Sheet1.Cells.Get(27, 10).Tag = "value3";
            this.neuSpread1_Sheet1.Cells.Get(27, 10).Value = 0;
            this.neuSpread1_Sheet1.Cells.Get(27, 11).Tag = "value3";
            this.neuSpread1_Sheet1.ColumnHeader.Visible = false;
            this.neuSpread1_Sheet1.Columns.Get(0).Width = 20F;
            this.neuSpread1_Sheet1.Columns.Get(1).Width = 100F;
            this.neuSpread1_Sheet1.Columns.Get(2).Width = 55F;
            this.neuSpread1_Sheet1.Columns.Get(3).Width = 40F;
            this.neuSpread1_Sheet1.Columns.Get(4).Width = 100F;
            this.neuSpread1_Sheet1.Columns.Get(5).Width = 55F;
            this.neuSpread1_Sheet1.Columns.Get(6).Width = 40F;
            this.neuSpread1_Sheet1.Columns.Get(7).Width = 65F;
            this.neuSpread1_Sheet1.Columns.Get(8).Width = 55F;
            this.neuSpread1_Sheet1.Columns.Get(9).Width = 55F;
            this.neuSpread1_Sheet1.Columns.Get(10).Width = 55F;
            this.neuSpread1_Sheet1.Columns.Get(11).Width = 55F;
            this.neuSpread1_Sheet1.Columns.Get(12).Width = 55F;
            this.neuSpread1_Sheet1.Columns.Get(13).Width = 20F;
            this.neuSpread1_Sheet1.Columns.Get(14).Width = 30F;
            this.neuSpread1_Sheet1.Columns.Get(15).Width = 50F;
            this.neuSpread1_Sheet1.Columns.Get(16).Width = 20F;
            this.neuSpread1_Sheet1.Columns.Get(17).Width = 30F;
            this.neuSpread1_Sheet1.Columns.Get(18).Width = 50F;
            this.neuSpread1_Sheet1.Columns.Get(19).Width = 20F;
            this.neuSpread1_Sheet1.Columns.Get(20).Width = 30F;
            this.neuSpread1_Sheet1.Columns.Get(21).Width = 50F;
            this.neuSpread1_Sheet1.DefaultStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.neuSpread1_Sheet1.DefaultStyle.Parent = "DataAreaDefault";
            this.neuSpread1_Sheet1.DefaultStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.neuSpread1_Sheet1.RowHeader.Columns.Default.Resizable = false;
            this.neuSpread1_Sheet1.RowHeader.Columns.Get(0).Width = 32F;
            this.neuSpread1_Sheet1.RowHeader.DefaultStyle.Parent = "HeaderDefault";
            this.neuSpread1_Sheet1.RowHeader.Visible = false;
            this.neuSpread1_Sheet1.Rows.Get(0).Height = 63F;
            this.neuSpread1_Sheet1.Rows.Get(1).Height = 30F;
            this.neuSpread1_Sheet1.Rows.Get(1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.neuSpread1_Sheet1.Rows.Get(1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.neuSpread1_Sheet1.Rows.Get(5).Height = 12F;
            this.neuSpread1_Sheet1.Rows.Get(6).Height = 12F;
            this.neuSpread1_Sheet1.Rows.Get(7).Height = 12F;
            this.neuSpread1_Sheet1.Rows.Get(8).Height = 12F;
            this.neuSpread1_Sheet1.Rows.Get(9).Height = 12F;
            this.neuSpread1_Sheet1.Rows.Get(10).Height = 12F;
            this.neuSpread1_Sheet1.Rows.Get(11).Height = 12F;
            this.neuSpread1_Sheet1.Rows.Get(12).Height = 12F;
            this.neuSpread1_Sheet1.Rows.Get(13).Height = 12F;
            this.neuSpread1_Sheet1.Rows.Get(14).Height = 12F;
            this.neuSpread1_Sheet1.Rows.Get(15).Height = 12F;
            this.neuSpread1_Sheet1.Rows.Get(16).Height = 12F;
            this.neuSpread1_Sheet1.Rows.Get(17).Height = 12F;
            this.neuSpread1_Sheet1.Rows.Get(18).Height = 12F;
            this.neuSpread1_Sheet1.Rows.Get(19).Height = 12F;
            this.neuSpread1_Sheet1.Rows.Get(20).Height = 12F;
            this.neuSpread1_Sheet1.Rows.Get(21).Height = 12F;
            this.neuSpread1_Sheet1.Rows.Get(22).Height = 12F;
            this.neuSpread1_Sheet1.Rows.Get(23).Height = 12F;
            this.neuSpread1_Sheet1.Rows.Get(24).Height = 12F;
            this.neuSpread1_Sheet1.Rows.Get(25).Height = 12F;
            this.neuSpread1_Sheet1.Rows.Get(26).Height = 12F;
            this.neuSpread1_Sheet1.VisualStyles = FarPoint.Win.VisualStyles.Off;
            this.neuSpread1_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.A1;
            // 
            // ucInvoicePrintFP
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.Control;
            this.Controls.Add(this.neuSpread1);
            this.Name = "ucInvoicePrintFP";
            this.Size = new System.Drawing.Size(1048, 470);
            ((System.ComponentModel.ISupportInitialize)(this.neuSpread1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.neuSpread1_Sheet1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Neusoft.FrameWork.WinForms.Controls.NeuSpread neuSpread1;
        private FarPoint.Win.Spread.SheetView neuSpread1_Sheet1;

    }
}
