//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3603
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neusoft.HISFC.Components.EPR.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neusoft.HISFC.Components.EPR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap explorer10 {
            get {
                object obj = ResourceManager.GetObject("explorer10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LabelPic {
            get {
                object obj = ResourceManager.GetObject("LabelPic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- Magic, The User Interface library for .NET (www.dotnetmagic.com) --&gt;
        ///&lt;!-- Modifying this generated file will probably render it invalid --&gt;
        ///&lt;DockingConfig FormatVersion=&quot;5&quot; InsideFill=&quot;False&quot; InnerMinimum=&quot;20, 20&quot;&gt;
        ///  &lt;Content Name=&quot;常用列表&quot; Visible=&quot;True&quot; Docked=&quot;True&quot; AutoHidden=&quot;False&quot; CaptionBar=&quot;True&quot; CloseButton=&quot;True&quot; DisplaySize=&quot;196, 980&quot; DisplayLocation=&quot;894, 583&quot; AutoHideSize=&quot;150, 150&quot; FloatingSize=&quot;200, 300&quot; FullTitle=&quot;常用列表(用鼠标拖到病历里面)&quot;&gt;
        ///    &lt;DefaultR [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string layout_default_epr {
            get {
                return ResourceManager.GetString("layout_default_epr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- Magic, The User Interface library for .NET (www.dotnetmagic.com) --&gt;
        ///&lt;!-- Modifying this generated file will probably render it invalid --&gt;
        ///&lt;DockingConfig FormatVersion=&quot;5&quot; InsideFill=&quot;False&quot; InnerMinimum=&quot;20, 20&quot;&gt;
        ///  &lt;Content Name=&quot;模板列表&quot; Visible=&quot;True&quot; Docked=&quot;True&quot; AutoHidden=&quot;True&quot; CaptionBar=&quot;True&quot; CloseButton=&quot;True&quot; DisplaySize=&quot;150, 150&quot; DisplayLocation=&quot;344, 155&quot; AutoHideSize=&quot;150, 150&quot; FloatingSize=&quot;200, 300&quot; FullTitle=&quot;模板列表&quot;&gt;
        ///    &lt;DefaultRestore Type= [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string layout_default_epr_vertical {
            get {
                return ResourceManager.GetString("layout_default_epr_vertical", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SPELL {
            get {
                object obj = ResourceManager.GetObject("SPELL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textbox {
            get {
                object obj = ResourceManager.GetObject("textbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 保存 {
            get {
                object obj = ResourceManager.GetObject("保存", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 修改 {
            get {
                object obj = ResourceManager.GetObject("修改", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 健康档案24 {
            get {
                object obj = ResourceManager.GetObject("健康档案24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 分解 {
            get {
                object obj = ResourceManager.GetObject("分解", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 刷新 {
            get {
                object obj = ResourceManager.GetObject("刷新", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 历史信息24 {
            get {
                object obj = ResourceManager.GetObject("历史信息24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 安排 {
            get {
                object obj = ResourceManager.GetObject("安排", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 手动录入24 {
            get {
                object obj = ResourceManager.GetObject("手动录入24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 打印 {
            get {
                object obj = ResourceManager.GetObject("打印", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 打印执行单16 {
            get {
                object obj = ResourceManager.GetObject("打印执行单16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 补打 {
            get {
                object obj = ResourceManager.GetObject("补打", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 设置24 {
            get {
                object obj = ResourceManager.GetObject("设置24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 转科确认 {
            get {
                object obj = ResourceManager.GetObject("转科确认", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
