namespace Neusoft.HISFC.Components.Registration.SelfReg
{
    partial class ucRegSelfHelp
    {
        /// <summary> 
        /// 必需的设计器变量。
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// 清理所有正在使用的资源。
        /// </summary>
        /// <param name="disposing">如果应释放托管资源，为 true；否则为 false。</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region 组件设计器生成的代码

        /// <summary> 
        /// 设计器支持所需的方法 - 不要
        /// 使用代码编辑器修改此方法的内容。
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            FarPoint.Win.Spread.TipAppearance tipAppearance1 = new FarPoint.Win.Spread.TipAppearance();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ucRegSelfHelp));
            this.neuLabel1 = new Neusoft.FrameWork.WinForms.Controls.NeuLabel();
            this.txtCardNO = new Neusoft.FrameWork.WinForms.Controls.NeuTextBox();
            this.btOk = new Neusoft.FrameWork.WinForms.Controls.NeuButton();
            this.btClear = new Neusoft.FrameWork.WinForms.Controls.NeuButton();
            this.btReadCard = new Neusoft.FrameWork.WinForms.Controls.NeuButton();
            this.btQuit = new Neusoft.FrameWork.WinForms.Controls.NeuButton();
            this.neuSpread1 = new Neusoft.FrameWork.WinForms.Controls.NeuSpread();
            this.neuSpread1_Sheet1 = new FarPoint.Win.Spread.SheetView();
            this.neuPictureBox1 = new Neusoft.FrameWork.WinForms.Controls.NeuPictureBox();
            this.neuPanel2 = new Neusoft.FrameWork.WinForms.Controls.NeuPanel();
            this.neuPictureBox2 = new Neusoft.FrameWork.WinForms.Controls.NeuPictureBox();
            this.neuPictureBox3 = new Neusoft.FrameWork.WinForms.Controls.NeuPictureBox();
            this.plLeft = new Neusoft.FrameWork.WinForms.Controls.NeuPanel();
            this.neuPanel5 = new Neusoft.FrameWork.WinForms.Controls.NeuPanel();
            this.lblDept = new Neusoft.FrameWork.WinForms.Controls.NeuLabel();
            this.txtDept = new Neusoft.FrameWork.WinForms.Controls.NeuTextBox();
            this.ucSelfHelpPatientInfo1 = new Neusoft.HISFC.Components.Registration.SelfReg.ucSelfHelpPatientInfo();
            this.neuPanel4 = new Neusoft.FrameWork.WinForms.Controls.NeuPanel();
            this.lblTip = new Neusoft.FrameWork.WinForms.Controls.NeuLabel();
            this.neuPictureBox4 = new Neusoft.FrameWork.WinForms.Controls.NeuPictureBox();
            this.neuPanel3 = new Neusoft.FrameWork.WinForms.Controls.NeuPanel();
            this.ptOper = new Neusoft.FrameWork.WinForms.Controls.NeuPictureBox();
            this.pbReadCard = new Neusoft.FrameWork.WinForms.Controls.NeuPictureBox();
            this.ptDept = new Neusoft.FrameWork.WinForms.Controls.NeuPictureBox();
            this.ptReg = new Neusoft.FrameWork.WinForms.Controls.NeuPictureBox();
            this.imageList1 = new System.Windows.Forms.ImageList(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.neuSpread1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.neuSpread1_Sheet1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.neuPictureBox1)).BeginInit();
            this.neuPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.neuPictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.neuPictureBox3)).BeginInit();
            this.plLeft.SuspendLayout();
            this.neuPanel5.SuspendLayout();
            this.neuPanel4.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.neuPictureBox4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ptOper)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbReadCard)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ptDept)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ptReg)).BeginInit();
            this.SuspendLayout();
            // 
            // neuLabel1
            // 
            this.neuLabel1.AutoSize = true;
            this.neuLabel1.Font = new System.Drawing.Font("宋体-方正超大字符集", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.neuLabel1.Location = new System.Drawing.Point(17, 18);
            this.neuLabel1.Name = "neuLabel1";
            this.neuLabel1.Size = new System.Drawing.Size(100, 21);
            this.neuLabel1.Style = Neusoft.FrameWork.WinForms.Controls.StyleType.Fixed3D;
            this.neuLabel1.TabIndex = 1;
            this.neuLabel1.Text = "就诊卡号:";
            // 
            // txtCardNO
            // 
            this.txtCardNO.Font = new System.Drawing.Font("宋体", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.txtCardNO.IsEnter2Tab = false;
            this.txtCardNO.Location = new System.Drawing.Point(117, 15);
            this.txtCardNO.Name = "txtCardNO";
            this.txtCardNO.Size = new System.Drawing.Size(149, 29);
            this.txtCardNO.Style = Neusoft.FrameWork.WinForms.Controls.StyleType.Fixed3D;
            this.txtCardNO.TabIndex = 0;
            this.txtCardNO.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txtCardNO_KeyDown);
            this.txtCardNO.Leave += new System.EventHandler(this.txtCardNO_Leave);
            this.txtCardNO.Enter += new System.EventHandler(this.txtCardNO_Enter);
            // 
            // btOk
            // 
            this.btOk.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.btOk.Font = new System.Drawing.Font("宋体", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.btOk.Location = new System.Drawing.Point(27, 700);
            this.btOk.Name = "btOk";
            this.btOk.Size = new System.Drawing.Size(81, 36);
            this.btOk.Style = Neusoft.FrameWork.WinForms.Controls.StyleType.Fixed3D;
            this.btOk.TabIndex = 0;
            this.btOk.Type = Neusoft.FrameWork.WinForms.Controls.General.ButtonType.None;
            this.btOk.UseVisualStyleBackColor = true;
            this.btOk.MouseLeave += new System.EventHandler(this.btClear_MouseLeave);
            this.btOk.MouseMove += new System.Windows.Forms.MouseEventHandler(this.btClear_MouseMove);
            this.btOk.Click += new System.EventHandler(this.btOk_Click);
            // 
            // btClear
            // 
            this.btClear.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.btClear.Font = new System.Drawing.Font("宋体", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.btClear.Location = new System.Drawing.Point(121, 700);
            this.btClear.Name = "btClear";
            this.btClear.Size = new System.Drawing.Size(81, 36);
            this.btClear.Style = Neusoft.FrameWork.WinForms.Controls.StyleType.Fixed3D;
            this.btClear.TabIndex = 1;
            this.btClear.Type = Neusoft.FrameWork.WinForms.Controls.General.ButtonType.None;
            this.btClear.UseVisualStyleBackColor = true;
            this.btClear.MouseLeave += new System.EventHandler(this.btClear_MouseLeave);
            this.btClear.MouseMove += new System.Windows.Forms.MouseEventHandler(this.btClear_MouseMove);
            this.btClear.Click += new System.EventHandler(this.btClear_Click);
            // 
            // btReadCard
            // 
            this.btReadCard.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.btReadCard.Font = new System.Drawing.Font("宋体", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.btReadCard.Location = new System.Drawing.Point(404, 703);
            this.btReadCard.Name = "btReadCard";
            this.btReadCard.Size = new System.Drawing.Size(81, 36);
            this.btReadCard.Style = Neusoft.FrameWork.WinForms.Controls.StyleType.Fixed3D;
            this.btReadCard.TabIndex = 2;
            this.btReadCard.Type = Neusoft.FrameWork.WinForms.Controls.General.ButtonType.None;
            this.btReadCard.UseVisualStyleBackColor = true;
            this.btReadCard.Visible = false;
            this.btReadCard.MouseLeave += new System.EventHandler(this.btClear_MouseLeave);
            this.btReadCard.MouseMove += new System.Windows.Forms.MouseEventHandler(this.btClear_MouseMove);
            this.btReadCard.Click += new System.EventHandler(this.btReadCard_Click);
            // 
            // btQuit
            // 
            this.btQuit.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.btQuit.Font = new System.Drawing.Font("宋体", 14.25F);
            this.btQuit.Location = new System.Drawing.Point(215, 700);
            this.btQuit.Name = "btQuit";
            this.btQuit.Size = new System.Drawing.Size(81, 36);
            this.btQuit.Style = Neusoft.FrameWork.WinForms.Controls.StyleType.Fixed3D;
            this.btQuit.TabIndex = 3;
            this.btQuit.Type = Neusoft.FrameWork.WinForms.Controls.General.ButtonType.None;
            this.btQuit.UseVisualStyleBackColor = true;
            this.btQuit.MouseLeave += new System.EventHandler(this.btClear_MouseLeave);
            this.btQuit.MouseMove += new System.Windows.Forms.MouseEventHandler(this.btClear_MouseMove);
            this.btQuit.Click += new System.EventHandler(this.btQuit_Click);
            // 
            // neuSpread1
            // 
            this.neuSpread1.About = "3.0.2004.2005";
            this.neuSpread1.AccessibleDescription = "neuSpread1, Sheet1, Row 0, Column 0, ";
            this.neuSpread1.BackColor = System.Drawing.Color.White;
            this.neuSpread1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.neuSpread1.FileName = "";
            this.neuSpread1.HorizontalScrollBarPolicy = FarPoint.Win.Spread.ScrollBarPolicy.AsNeeded;
            this.neuSpread1.IsAutoSaveGridStatus = false;
            this.neuSpread1.IsCanCustomConfigColumn = false;
            this.neuSpread1.Location = new System.Drawing.Point(570, 152);
            this.neuSpread1.Name = "neuSpread1";
            this.neuSpread1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.neuSpread1.Sheets.AddRange(new FarPoint.Win.Spread.SheetView[] {
            this.neuSpread1_Sheet1});
            this.neuSpread1.Size = new System.Drawing.Size(442, 545);
            this.neuSpread1.Style = Neusoft.FrameWork.WinForms.Controls.StyleType.Fixed3D;
            this.neuSpread1.TabIndex = 1;
            tipAppearance1.BackColor = System.Drawing.SystemColors.Info;
            tipAppearance1.Font = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            tipAppearance1.ForeColor = System.Drawing.SystemColors.InfoText;
            this.neuSpread1.TextTipAppearance = tipAppearance1;
            this.neuSpread1.VerticalScrollBarPolicy = FarPoint.Win.Spread.ScrollBarPolicy.AsNeeded;
            this.neuSpread1.ButtonClicked += new FarPoint.Win.Spread.EditorNotifyEventHandler(this.neuSpread1_ButtonClicked);
            // 
            // neuSpread1_Sheet1
            // 
            this.neuSpread1_Sheet1.Reset();
            this.neuSpread1_Sheet1.SheetName = "Sheet1";
            // Formulas and custom names must be loaded with R1C1 reference style
            this.neuSpread1_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.R1C1;
            this.neuSpread1_Sheet1.ColumnHeader.RowCount = 0;
            this.neuSpread1_Sheet1.RowHeader.ColumnCount = 0;
            this.neuSpread1_Sheet1.Columns.Get(0).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(1).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(2).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(3).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(4).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(5).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(6).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(7).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(8).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(9).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(10).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(11).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(12).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(13).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(14).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(15).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(16).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(17).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(18).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(19).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(20).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(21).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(22).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(23).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(24).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(25).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(26).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(27).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(28).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(29).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(30).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(31).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(32).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(33).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(34).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(35).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(36).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(37).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(38).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(39).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(40).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(41).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(42).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(43).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(44).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(45).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(46).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(47).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(48).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(49).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(50).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(51).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(52).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(53).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(54).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(55).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(56).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(57).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(58).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(59).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(60).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(61).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(62).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(63).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(64).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(65).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(66).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(67).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(68).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(69).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(70).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(71).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(72).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(73).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(74).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(75).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(76).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(77).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(78).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(79).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(80).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(81).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(82).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(83).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(84).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(85).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(86).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(87).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(88).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(89).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(90).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(91).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(92).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(93).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(94).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(95).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(96).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(97).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(98).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(99).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(100).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(101).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(102).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(103).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(104).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(105).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(106).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(107).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(108).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(109).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(110).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(111).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(112).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(113).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(114).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(115).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(116).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(117).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(118).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(119).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(120).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(121).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(122).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(123).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(124).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(125).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(126).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(127).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(128).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(129).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(130).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(131).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(132).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(133).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(134).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(135).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(136).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(137).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(138).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(139).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(140).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(141).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(142).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(143).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(144).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(145).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(146).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(147).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(148).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(149).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(150).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(151).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(152).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(153).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(154).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(155).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(156).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(157).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(158).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(159).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(160).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(161).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(162).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(163).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(164).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(165).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(166).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(167).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(168).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(169).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(170).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(171).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(172).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(173).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(174).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(175).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(176).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(177).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(178).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(179).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(180).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(181).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(182).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(183).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(184).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(185).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(186).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(187).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(188).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(189).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(190).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(191).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(192).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(193).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(194).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(195).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(196).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(197).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(198).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(199).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(200).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(201).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(202).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(203).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(204).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(205).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(206).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(207).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(208).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(209).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(210).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(211).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(212).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(213).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(214).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(215).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(216).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(217).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(218).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(219).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(220).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(221).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(222).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(223).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(224).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(225).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(226).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(227).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(228).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(229).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(230).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(231).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(232).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(233).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(234).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(235).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(236).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(237).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(238).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(239).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(240).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(241).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(242).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(243).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(244).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(245).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(246).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(247).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(248).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(249).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(250).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(251).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(252).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(253).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(254).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(255).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(256).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(257).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(258).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(259).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(260).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(261).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(262).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(263).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(264).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(265).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(266).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(267).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(268).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(269).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(270).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(271).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(272).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(273).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(274).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(275).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(276).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(277).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(278).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(279).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(280).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(281).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(282).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(283).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(284).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(285).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(286).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(287).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(288).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(289).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(290).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(291).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(292).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(293).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(294).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(295).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(296).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(297).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(298).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(299).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(300).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(301).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(302).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(303).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(304).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(305).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(306).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(307).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(308).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(309).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(310).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(311).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(312).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(313).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(314).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(315).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(316).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(317).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(318).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(319).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(320).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(321).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(322).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(323).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(324).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(325).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(326).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(327).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(328).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(329).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(330).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(331).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(332).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(333).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(334).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(335).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(336).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(337).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(338).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(339).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(340).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(341).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(342).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(343).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(344).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(345).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(346).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(347).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(348).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(349).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(350).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(351).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(352).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(353).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(354).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(355).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(356).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(357).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(358).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(359).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(360).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(361).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(362).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(363).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(364).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(365).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(366).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(367).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(368).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(369).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(370).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(371).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(372).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(373).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(374).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(375).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(376).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(377).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(378).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(379).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(380).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(381).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(382).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(383).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(384).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(385).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(386).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(387).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(388).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(389).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(390).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(391).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(392).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(393).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(394).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(395).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(396).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(397).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(398).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(399).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(400).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(401).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(402).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(403).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(404).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(405).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(406).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(407).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(408).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(409).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(410).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(411).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(412).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(413).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(414).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(415).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(416).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(417).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(418).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(419).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(420).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(421).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(422).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(423).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(424).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(425).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(426).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(427).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(428).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(429).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(430).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(431).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(432).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(433).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(434).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(435).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(436).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(437).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(438).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(439).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(440).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(441).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(442).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(443).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(444).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(445).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(446).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(447).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(448).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(449).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(450).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(451).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(452).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(453).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(454).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(455).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(456).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(457).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(458).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(459).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(460).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(461).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(462).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(463).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(464).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(465).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(466).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(467).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(468).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(469).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(470).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(471).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(472).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(473).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(474).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(475).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(476).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(477).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(478).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(479).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(480).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(481).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(482).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(483).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(484).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(485).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(486).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(487).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(488).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(489).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(490).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(491).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(492).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(493).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(494).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(495).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(496).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(497).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(498).Width = 121F;
            this.neuSpread1_Sheet1.Columns.Get(499).Width = 121F;
            this.neuSpread1_Sheet1.GrayAreaBackColor = System.Drawing.Color.White;
            this.neuSpread1_Sheet1.RowHeader.Columns.Default.Resizable = false;
            this.neuSpread1_Sheet1.Rows.Get(0).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(1).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(2).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(3).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(4).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(5).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(6).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(7).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(8).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(9).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(10).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(11).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(12).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(13).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(14).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(15).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(16).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(17).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(18).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(19).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(20).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(21).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(22).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(23).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(24).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(25).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(26).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(27).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(28).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(29).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(30).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(31).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(32).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(33).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(34).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(35).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(36).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(37).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(38).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(39).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(40).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(41).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(42).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(43).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(44).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(45).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(46).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(47).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(48).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(49).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(50).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(51).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(52).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(53).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(54).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(55).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(56).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(57).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(58).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(59).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(60).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(61).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(62).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(63).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(64).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(65).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(66).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(67).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(68).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(69).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(70).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(71).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(72).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(73).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(74).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(75).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(76).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(77).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(78).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(79).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(80).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(81).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(82).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(83).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(84).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(85).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(86).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(87).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(88).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(89).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(90).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(91).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(92).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(93).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(94).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(95).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(96).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(97).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(98).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(99).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(100).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(101).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(102).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(103).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(104).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(105).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(106).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(107).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(108).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(109).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(110).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(111).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(112).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(113).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(114).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(115).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(116).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(117).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(118).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(119).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(120).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(121).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(122).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(123).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(124).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(125).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(126).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(127).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(128).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(129).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(130).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(131).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(132).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(133).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(134).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(135).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(136).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(137).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(138).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(139).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(140).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(141).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(142).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(143).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(144).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(145).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(146).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(147).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(148).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(149).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(150).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(151).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(152).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(153).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(154).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(155).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(156).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(157).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(158).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(159).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(160).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(161).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(162).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(163).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(164).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(165).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(166).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(167).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(168).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(169).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(170).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(171).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(172).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(173).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(174).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(175).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(176).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(177).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(178).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(179).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(180).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(181).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(182).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(183).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(184).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(185).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(186).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(187).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(188).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(189).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(190).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(191).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(192).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(193).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(194).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(195).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(196).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(197).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(198).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(199).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(200).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(201).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(202).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(203).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(204).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(205).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(206).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(207).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(208).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(209).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(210).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(211).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(212).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(213).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(214).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(215).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(216).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(217).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(218).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(219).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(220).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(221).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(222).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(223).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(224).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(225).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(226).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(227).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(228).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(229).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(230).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(231).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(232).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(233).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(234).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(235).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(236).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(237).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(238).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(239).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(240).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(241).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(242).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(243).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(244).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(245).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(246).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(247).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(248).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(249).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(250).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(251).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(252).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(253).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(254).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(255).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(256).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(257).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(258).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(259).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(260).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(261).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(262).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(263).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(264).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(265).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(266).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(267).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(268).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(269).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(270).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(271).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(272).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(273).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(274).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(275).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(276).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(277).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(278).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(279).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(280).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(281).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(282).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(283).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(284).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(285).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(286).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(287).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(288).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(289).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(290).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(291).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(292).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(293).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(294).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(295).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(296).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(297).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(298).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(299).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(300).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(301).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(302).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(303).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(304).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(305).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(306).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(307).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(308).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(309).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(310).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(311).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(312).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(313).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(314).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(315).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(316).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(317).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(318).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(319).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(320).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(321).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(322).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(323).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(324).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(325).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(326).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(327).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(328).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(329).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(330).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(331).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(332).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(333).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(334).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(335).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(336).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(337).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(338).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(339).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(340).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(341).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(342).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(343).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(344).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(345).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(346).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(347).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(348).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(349).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(350).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(351).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(352).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(353).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(354).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(355).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(356).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(357).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(358).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(359).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(360).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(361).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(362).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(363).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(364).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(365).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(366).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(367).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(368).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(369).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(370).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(371).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(372).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(373).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(374).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(375).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(376).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(377).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(378).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(379).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(380).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(381).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(382).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(383).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(384).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(385).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(386).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(387).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(388).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(389).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(390).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(391).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(392).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(393).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(394).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(395).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(396).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(397).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(398).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(399).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(400).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(401).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(402).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(403).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(404).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(405).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(406).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(407).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(408).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(409).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(410).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(411).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(412).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(413).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(414).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(415).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(416).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(417).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(418).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(419).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(420).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(421).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(422).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(423).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(424).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(425).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(426).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(427).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(428).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(429).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(430).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(431).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(432).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(433).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(434).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(435).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(436).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(437).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(438).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(439).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(440).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(441).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(442).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(443).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(444).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(445).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(446).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(447).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(448).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(449).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(450).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(451).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(452).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(453).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(454).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(455).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(456).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(457).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(458).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(459).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(460).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(461).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(462).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(463).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(464).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(465).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(466).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(467).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(468).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(469).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(470).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(471).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(472).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(473).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(474).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(475).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(476).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(477).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(478).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(479).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(480).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(481).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(482).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(483).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(484).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(485).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(486).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(487).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(488).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(489).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(490).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(491).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(492).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(493).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(494).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(495).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(496).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(497).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(498).Height = 96F;
            this.neuSpread1_Sheet1.Rows.Get(499).Height = 96F;
            this.neuSpread1_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.A1;
            // 
            // neuPictureBox1
            // 
            this.neuPictureBox1.Dock = System.Windows.Forms.DockStyle.Top;
            this.neuPictureBox1.Image = global::Neusoft.HISFC.Components.Registration.Properties.Resources.上1;
            this.neuPictureBox1.Location = new System.Drawing.Point(0, 0);
            this.neuPictureBox1.Name = "neuPictureBox1";
            this.neuPictureBox1.Size = new System.Drawing.Size(1012, 30);
            this.neuPictureBox1.Style = Neusoft.FrameWork.WinForms.Controls.StyleType.Fixed3D;
            this.neuPictureBox1.TabIndex = 6;
            this.neuPictureBox1.TabStop = false;
            // 
            // neuPanel2
            // 
            this.neuPanel2.Controls.Add(this.neuLabel1);
            this.neuPanel2.Controls.Add(this.txtCardNO);
            this.neuPanel2.Dock = System.Windows.Forms.DockStyle.Top;
            this.neuPanel2.Location = new System.Drawing.Point(0, 30);
            this.neuPanel2.Name = "neuPanel2";
            this.neuPanel2.Size = new System.Drawing.Size(1012, 64);
            this.neuPanel2.Style = Neusoft.FrameWork.WinForms.Controls.StyleType.Fixed3D;
            this.neuPanel2.TabIndex = 7;
            // 
            // neuPictureBox2
            // 
            this.neuPictureBox2.Dock = System.Windows.Forms.DockStyle.Top;
            this.neuPictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("neuPictureBox2.Image")));
            this.neuPictureBox2.Location = new System.Drawing.Point(0, 94);
            this.neuPictureBox2.Name = "neuPictureBox2";
            this.neuPictureBox2.Size = new System.Drawing.Size(1012, 48);
            this.neuPictureBox2.Style = Neusoft.FrameWork.WinForms.Controls.StyleType.Fixed3D;
            this.neuPictureBox2.TabIndex = 8;
            this.neuPictureBox2.TabStop = false;
            // 
            // neuPictureBox3
            // 
            this.neuPictureBox3.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.neuPictureBox3.Image = global::Neusoft.HISFC.Components.Registration.Properties.Resources.上5;
            this.neuPictureBox3.Location = new System.Drawing.Point(0, 697);
            this.neuPictureBox3.Name = "neuPictureBox3";
            this.neuPictureBox3.Size = new System.Drawing.Size(1012, 44);
            this.neuPictureBox3.Style = Neusoft.FrameWork.WinForms.Controls.StyleType.Fixed3D;
            this.neuPictureBox3.TabIndex = 10;
            this.neuPictureBox3.TabStop = false;
            // 
            // plLeft
            // 
            this.plLeft.Controls.Add(this.neuPanel5);
            this.plLeft.Controls.Add(this.neuPanel4);
            this.plLeft.Dock = System.Windows.Forms.DockStyle.Left;
            this.plLeft.Location = new System.Drawing.Point(0, 142);
            this.plLeft.Name = "plLeft";
            this.plLeft.Size = new System.Drawing.Size(570, 555);
            this.plLeft.Style = Neusoft.FrameWork.WinForms.Controls.StyleType.Fixed3D;
            this.plLeft.TabIndex = 11;
            // 
            // neuPanel5
            // 
            this.neuPanel5.Controls.Add(this.lblDept);
            this.neuPanel5.Controls.Add(this.txtDept);
            this.neuPanel5.Controls.Add(this.ucSelfHelpPatientInfo1);
            this.neuPanel5.Dock = System.Windows.Forms.DockStyle.Fill;
            this.neuPanel5.Location = new System.Drawing.Point(0, 0);
            this.neuPanel5.Name = "neuPanel5";
            this.neuPanel5.Size = new System.Drawing.Size(570, 361);
            this.neuPanel5.Style = Neusoft.FrameWork.WinForms.Controls.StyleType.Fixed3D;
            this.neuPanel5.TabIndex = 2;
            // 
            // lblDept
            // 
            this.lblDept.AutoSize = true;
            this.lblDept.Font = new System.Drawing.Font("宋体", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.lblDept.Location = new System.Drawing.Point(24, 316);
            this.lblDept.Name = "lblDept";
            this.lblDept.Size = new System.Drawing.Size(80, 16);
            this.lblDept.Style = Neusoft.FrameWork.WinForms.Controls.StyleType.Fixed3D;
            this.lblDept.TabIndex = 2;
            this.lblDept.Text = "挂号科室:";
            // 
            // txtDept
            // 
            this.txtDept.Font = new System.Drawing.Font("宋体", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.txtDept.IsEnter2Tab = false;
            this.txtDept.Location = new System.Drawing.Point(121, 312);
            this.txtDept.Name = "txtDept";
            this.txtDept.Size = new System.Drawing.Size(127, 26);
            this.txtDept.Style = Neusoft.FrameWork.WinForms.Controls.StyleType.Fixed3D;
            this.txtDept.TabIndex = 1;
            this.txtDept.Leave += new System.EventHandler(this.txtDept_Leave);
            this.txtDept.Enter += new System.EventHandler(this.txtDept_Enter);
            // 
            // ucSelfHelpPatientInfo1
            // 
            this.ucSelfHelpPatientInfo1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucSelfHelpPatientInfo1.Font = new System.Drawing.Font("宋体-方正超大字符集", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.ucSelfHelpPatientInfo1.Location = new System.Drawing.Point(0, 0);
            this.ucSelfHelpPatientInfo1.Name = "ucSelfHelpPatientInfo1";
            this.ucSelfHelpPatientInfo1.Size = new System.Drawing.Size(570, 361);
            this.ucSelfHelpPatientInfo1.TabIndex = 0;
            // 
            // neuPanel4
            // 
            this.neuPanel4.Controls.Add(this.lblTip);
            this.neuPanel4.Controls.Add(this.neuPictureBox4);
            this.neuPanel4.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.neuPanel4.Location = new System.Drawing.Point(0, 361);
            this.neuPanel4.Name = "neuPanel4";
            this.neuPanel4.Size = new System.Drawing.Size(570, 194);
            this.neuPanel4.Style = Neusoft.FrameWork.WinForms.Controls.StyleType.Fixed3D;
            this.neuPanel4.TabIndex = 1;
            // 
            // lblTip
            // 
            this.lblTip.AutoSize = true;
            this.lblTip.Location = new System.Drawing.Point(115, 117);
            this.lblTip.Name = "lblTip";
            this.lblTip.Size = new System.Drawing.Size(59, 12);
            this.lblTip.Style = Neusoft.FrameWork.WinForms.Controls.StyleType.Fixed3D;
            this.lblTip.TabIndex = 1;
            this.lblTip.Text = "neuLabel2";
            // 
            // neuPictureBox4
            // 
            this.neuPictureBox4.Image = ((System.Drawing.Image)(resources.GetObject("neuPictureBox4.Image")));
            this.neuPictureBox4.Location = new System.Drawing.Point(21, 31);
            this.neuPictureBox4.Name = "neuPictureBox4";
            this.neuPictureBox4.Size = new System.Drawing.Size(153, 50);
            this.neuPictureBox4.Style = Neusoft.FrameWork.WinForms.Controls.StyleType.Fixed3D;
            this.neuPictureBox4.TabIndex = 0;
            this.neuPictureBox4.TabStop = false;
            // 
            // neuPanel3
            // 
            this.neuPanel3.Dock = System.Windows.Forms.DockStyle.Top;
            this.neuPanel3.Location = new System.Drawing.Point(570, 142);
            this.neuPanel3.Name = "neuPanel3";
            this.neuPanel3.Size = new System.Drawing.Size(442, 10);
            this.neuPanel3.Style = Neusoft.FrameWork.WinForms.Controls.StyleType.Fixed3D;
            this.neuPanel3.TabIndex = 12;
            // 
            // ptOper
            // 
            this.ptOper.Image = global::Neusoft.HISFC.Components.Registration.Properties.Resources.操作指南_1;
            this.ptOper.Location = new System.Drawing.Point(570, 96);
            this.ptOper.Name = "ptOper";
            this.ptOper.Size = new System.Drawing.Size(96, 41);
            this.ptOper.Style = Neusoft.FrameWork.WinForms.Controls.StyleType.Fixed3D;
            this.ptOper.TabIndex = 13;
            this.ptOper.TabStop = false;
            // 
            // pbReadCard
            // 
            this.pbReadCard.Image = global::Neusoft.HISFC.Components.Registration.Properties.Resources.刷卡_1;
            this.pbReadCard.Location = new System.Drawing.Point(667, 97);
            this.pbReadCard.Name = "pbReadCard";
            this.pbReadCard.Size = new System.Drawing.Size(96, 40);
            this.pbReadCard.Style = Neusoft.FrameWork.WinForms.Controls.StyleType.Fixed3D;
            this.pbReadCard.TabIndex = 14;
            this.pbReadCard.TabStop = false;
            // 
            // ptDept
            // 
            this.ptDept.Image = global::Neusoft.HISFC.Components.Registration.Properties.Resources.点击右侧_1;
            this.ptDept.Location = new System.Drawing.Point(764, 97);
            this.ptDept.Name = "ptDept";
            this.ptDept.Size = new System.Drawing.Size(96, 40);
            this.ptDept.Style = Neusoft.FrameWork.WinForms.Controls.StyleType.Fixed3D;
            this.ptDept.TabIndex = 15;
            this.ptDept.TabStop = false;
            // 
            // ptReg
            // 
            this.ptReg.Image = global::Neusoft.HISFC.Components.Registration.Properties.Resources.点击挂号_1;
            this.ptReg.Location = new System.Drawing.Point(862, 97);
            this.ptReg.Name = "ptReg";
            this.ptReg.Size = new System.Drawing.Size(115, 40);
            this.ptReg.Style = Neusoft.FrameWork.WinForms.Controls.StyleType.Fixed3D;
            this.ptReg.TabIndex = 16;
            this.ptReg.TabStop = false;
            // 
            // imageList1
            // 
            this.imageList1.ColorDepth = System.Windows.Forms.ColorDepth.Depth8Bit;
            this.imageList1.ImageSize = new System.Drawing.Size(16, 16);
            this.imageList1.TransparentColor = System.Drawing.Color.Transparent;
            // 
            // ucRegSelfHelp
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.GhostWhite;
            this.ClientSize = new System.Drawing.Size(1012, 741);
            this.Controls.Add(this.ptReg);
            this.Controls.Add(this.ptDept);
            this.Controls.Add(this.pbReadCard);
            this.Controls.Add(this.ptOper);
            this.Controls.Add(this.btClear);
            this.Controls.Add(this.btReadCard);
            this.Controls.Add(this.btQuit);
            this.Controls.Add(this.btOk);
            this.Controls.Add(this.neuSpread1);
            this.Controls.Add(this.neuPanel3);
            this.Controls.Add(this.plLeft);
            this.Controls.Add(this.neuPictureBox3);
            this.Controls.Add(this.neuPictureBox2);
            this.Controls.Add(this.neuPanel2);
            this.Controls.Add(this.neuPictureBox1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "ucRegSelfHelp";
            ((System.ComponentModel.ISupportInitialize)(this.neuSpread1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.neuSpread1_Sheet1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.neuPictureBox1)).EndInit();
            this.neuPanel2.ResumeLayout(false);
            this.neuPanel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.neuPictureBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.neuPictureBox3)).EndInit();
            this.plLeft.ResumeLayout(false);
            this.neuPanel5.ResumeLayout(false);
            this.neuPanel5.PerformLayout();
            this.neuPanel4.ResumeLayout(false);
            this.neuPanel4.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.neuPictureBox4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ptOper)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbReadCard)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ptDept)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ptReg)).EndInit();
            this.ResumeLayout(false);

        }

       
       

       
        #endregion

        private Neusoft.FrameWork.WinForms.Controls.NeuLabel neuLabel1;
        private Neusoft.FrameWork.WinForms.Controls.NeuTextBox txtCardNO;
        private Neusoft.FrameWork.WinForms.Controls.NeuButton btOk;
        private Neusoft.FrameWork.WinForms.Controls.NeuButton btClear;
        private Neusoft.FrameWork.WinForms.Controls.NeuButton btReadCard;
        private Neusoft.FrameWork.WinForms.Controls.NeuSpread neuSpread1;
        private FarPoint.Win.Spread.SheetView neuSpread1_Sheet1;
        private Neusoft.FrameWork.WinForms.Controls.NeuButton btQuit;
        private Neusoft.FrameWork.WinForms.Controls.NeuPictureBox neuPictureBox1;
        private Neusoft.FrameWork.WinForms.Controls.NeuPanel neuPanel2;
        private Neusoft.FrameWork.WinForms.Controls.NeuPictureBox neuPictureBox2;
        private Neusoft.FrameWork.WinForms.Controls.NeuPictureBox neuPictureBox3;
        private Neusoft.FrameWork.WinForms.Controls.NeuPanel plLeft;
        private Neusoft.FrameWork.WinForms.Controls.NeuPanel neuPanel3;
        private Neusoft.FrameWork.WinForms.Controls.NeuPanel neuPanel5;
        private ucSelfHelpPatientInfo ucSelfHelpPatientInfo1;
        private Neusoft.FrameWork.WinForms.Controls.NeuPanel neuPanel4;
        private Neusoft.FrameWork.WinForms.Controls.NeuPictureBox neuPictureBox4;
        private Neusoft.FrameWork.WinForms.Controls.NeuLabel lblTip;
        private Neusoft.FrameWork.WinForms.Controls.NeuTextBox txtDept;
        private Neusoft.FrameWork.WinForms.Controls.NeuLabel lblDept;
        private Neusoft.FrameWork.WinForms.Controls.NeuPictureBox ptOper;
        private Neusoft.FrameWork.WinForms.Controls.NeuPictureBox pbReadCard;
        private Neusoft.FrameWork.WinForms.Controls.NeuPictureBox ptDept;
        private Neusoft.FrameWork.WinForms.Controls.NeuPictureBox ptReg;
        private System.Windows.Forms.ImageList imageList1;
    }
}
